config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'images/process_img', to: 'images#process_img'
  resources :images
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/images_controller.rb
require 'mini_magick'
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)
    @image.file.attach(params[:image][:file])

    # binding.irb

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy!

    respond_to do |format|
      format.html { redirect_to images_path, status: :see_other, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def process_img
    # ProcessImageJob.perform_in(1.minutes, params[:image_id], params[:process_name])
    img = Image.find(params[:image_id])

    if img.status != "ready"
      render json: { message: "Image is already being processed", status: 400 }
      return
    end

    img.status = "processing"
    img.save!

    # binding.irb

    time = 0

    if params[:process_name] == "dilated"
      ProcessDilateJob.perform_later(params[:image_id])
      # ProcessDilateJob.set(wait: time.seconds).perform_later(params[:image_id])
    elsif params[:process_name] == "erode"
      ProcessErodeJob.perform_later(params[:image_id])
    end

    render json: { message: "Processing started", status: 202, time: "#{time.to_s} segundos"}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.expect(image: [ :name, :description ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true, html: { multipart: true, class: "form-container" }) do |form| %>
  <div class="form-group">
    <%= form.label :name, "Nome da Imagem" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Digite o nome da imagem" %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Descrição" %>
    <%= form.text_area :description, class: "form-control", placeholder: "Escreva uma descrição" %>
  </div>

  <div class="form-group">
    <%= form.label :file, "Escolha o Arquivo" %>
    <%= form.file_field :file, class: "form-control-file" %>
  </div>

  <div class="form-actions">
    <%= form.submit "Salvar Imagem", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">

  <div class="image-wrapper" >
    <% if image.file.attached? %>
      <%= image_tag image.file %>
    <% end %>
    <p>
      <strong>Name:</strong>
      <%= image.name %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= image.description %>
    </p>
    <p class="bg-wrapper">
      <strong>STATUS: </strong>
      <% if image.status == "ready" %>
        <span class="bg-status bg-success" data-bg-id="<%= image.id %>">Pronto</span>
      <% else %>
        <span class="bg-status bg-warning" data-bg-id="<%= image.id %>">Processando</span>
      <% end %>
    </p>
    <div class = "row">
      <div id="process-img" data-operation="erode" data-id="<%=image.id %>" class="btn btn-primary">Aplicar Erosão</div>
      <div id="process-img" data-operation="dilated" data-id="<%=image.id %>" class="btn btn-dark">Aplicar Dilatação</div>
    </div>
  </div>

</div>

app/views/images/edit.html.erb
<% content_for :title, "Editing image" %>

<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<% content_for :extra_js do %>
  <%= javascript_include_tag "images", defer: true, "data-turbo-track": "reload" %>
<% end %>

<p style="color: green"><%= notice %></p>

<% content_for :title, "Images" %>

<h2>Images</h2>

<div class="img-list">
  <% @images.each do |image| %>
    <div class="image-wrapper" data-id="<%=image.id %>">
      <%= render image %>
      <p>
        <%= link_to "Show this image", image %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New image", new_image_path %>

app/views/images/new.html.erb
<% content_for :title, "New image" %>

<h1>New image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Img Processing" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= action_cable_meta_tag %>
    <%= javascript_importmap_tags %>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= yield :extra_js %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>